[package]
name = "kalosm-model-types"
version = "0.4.0"
edition = "2021"
description = "Shared types for Kalosm models"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["llm", "llama", "mistral", "agents", "nlp"]

[dependencies]
indicatif = { version = "0.17.8", optional = true }

[features]
loading-progress-bar = ["dep:indicatif"]
