[package]
name = "kalosm-parse-macro"
version = "0.4.0"
edition = "2021"
description = "A macro to derive kalosm parsing traits"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["ai", "bert", "nlp", "machine-learning", "transformers"]

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.86"

[dev-dependencies]
kalosm = { workspace = true, features = ["language"], default-features = true }
serde_json = "1.0.122"
tokio = { version = "1.28.1", features = ["full"] }
pretty_assertions = "1.4.0"

[features]
metal = []
cuda = []

[lib]
proc-macro = true
