---

- name: Destroy
  hosts: localhost
  connection: local
  vars:
    molecule_file: "{{ lookup('env', 'MOLECULE_FILE') }}"
    molecule_instance_config: "{{ lookup('env',' MOLECULE_INSTANCE_CONFIG') }}"
    molecule_yml: "{{ lookup('file', molecule_file) | from_yaml }}"
    molecule_ephemeral_directory: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}"
  tasks:
    - name: Check that Qubes admin tools are installed
      shell: >
        which qvm-clone
        || { echo 'qvm-clone not found, install qubes-core-admin-client';
        exit 1; }
      changed_when: false

    - name: Halt molecule instance(s)
      command: qvm-shutdown --wait "{{ item.vm_name }}"
      register: server
      failed_when: >-
         server.rc != 0 and "qvm-shutdown: error: no such domain: '"+item.vm_name+"'" not in server.stderr_lines
      loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"

    - name: Destroy molecule instance(s)
      command: qvm-remove --force "{{ item.vm_name }}"
      register: server
      failed_when: >-
         server.rc != 0 and "qvm-remove: error: no such domain: '"+item.vm_name+"'" not in server.stderr_lines
      loop: "{{ molecule_yml.platforms | flatten(levels=1) }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config
      set_fact:
        instance_conf: {}

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed
          {{ instance_conf | to_json | from_json | to_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
