site_name: lib-bpmn-engine
site_url: https://nitram509.github.io/lib-bpmn-engine/

theme:
  name: material
  logo: images/gopher-lib-bpmn-engine.svg

repo_url: https://github.com/nitram509/lib-bpmn-engine

#lang: en

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Advanced Examples:
      - 'Microservice & REST API': advanced-microservice.md
      - 'Zeebe Exporter (visualization)': advanced-zeebe.md
      - 'Timers & Schedulers': advanced-timers.md
      - 'Multiple BPMN process versions': advanced-multiple-versions.md
      - 'Persistence (marshalling)': advanced-persistence.md
  - Supported Elements: supported-elements.md
  - Implementation Notes/Guidelines:
      - IDs (process IDs): implementation-ids.md
      - Task Handlers: implementation-task-handlers.md
  - Modelling Notes/Guidelines:
      - Expression Syntax: expression-syntax.md
  - Roadmap: roadmap.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

extra_css:
  - stylesheets/extra.css
