[package]
name = "kalosm-learning-macro"
version = "0.4.0"
edition = "2021"
description = "A macro to derive kalosm learning traits"
license = "MIT/Apache-2.0"
repository = "https://github.com/floneum/floneum"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
keywords = ["ai", "bert", "nlp", "machine-learning", "transformers"]

[dependencies]
syn = "2.0"
quote = "1.0"

[lib]
proc-macro = true
