os: linux
dist: jammy
language: python
python: "3.12"

branches:
  except:
    - /^dependabot.*$/

jobs:
  include:
  - arch: ppc64le
  - arch: s390x
  allow_failures:
  - arch: ppc64le

addons:
  apt:
    packages:
    - qemu-user-static

services:
  - docker

notifications:
  email: false

install:
  - curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
  - curl -fsSLo ${HOME}/codecov.SHA256SUM https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
  - curl -fsSLo ${HOME}/codecov.SHA256SUM.sig https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
  - curl -fsSLo ${HOME}/codecov https://uploader.codecov.io/latest/linux/codecov
  - gpgv ${HOME}/codecov.SHA256SUM.sig ${HOME}/codecov.SHA256SUM
  - pushd ${HOME} && shasum -a 256 -c codecov.SHA256SUM && popd
  - chmod +x ${HOME}/codecov
  - qemu-x86_64-static ${HOME}/codecov --version
  - pip install nox

script:
  - nox -s tests-3.12

after_success:
  - qemu-x86_64-static ${HOME}/codecov

cache:
  directories:
    - $HOME/.cache/auditwheel_tests
