[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "redwood"
version = "0.1.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
]

[tool.setuptools]
packages = ["redwood"]
