name: update gh-pages
on:
  push:
    branches:
      - master
      - main
jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r doc-requirements.txt
      - run: mkdocs gh-deploy --force
